plugins {
    id("com.android.library") version "8.7.3" apply false
    kotlin("android") version "2.1.0" apply false
    kotlin("jvm") version "2.1.0" apply false
}

// The bindings, generated by uniffi-bindgen.
extra["uniffiSources"] = layout.buildDirectory.dir("generated/uniffi").get().asFile
// The Android libraries, built by cargo-ndk.
extra["jniLibs"] = layout.buildDirectory.dir("jniLibs").get().asFile
