[package]
name = "herder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "herder"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
herder-daemon.workspace = true
herder-tui.workspace = true

[dev-dependencies]
nix.workspace = true
tempfile.workspace = true

[lints]
workspace = true
