[package]
name = "herder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "herder"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
flate2.workspace = true
herder-adapters.workspace = true
herder-daemon.workspace = true
herder-protocol.workspace = true
herder-tui.workspace = true
qrcode.workspace = true
semver.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "io-std", "io-util", "process"] }
ureq.workspace = true

[dev-dependencies]
nix.workspace = true
serde_json.workspace = true

[lints]
workspace = true
