// The AAR the app links: the Kotlin bindings of crates/herder-ffi, generated by uniffi-bindgen,
// and its Android libraries, built by cargo-ndk. Both are built from the workspace on every
// build; cargo skips what has not changed.

plugins {
    alias(libs.plugins.android.library)
}

val repo: File = rootDir.parentFile

android {
    namespace = "sh.herder.ffi"
    compileSdk = 37
    defaultConfig {
        minSdk = 26
        consumerProguardFiles(repo.resolve("crates/herder-ffi/kotlin/android/consumer-rules.pro"))
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    api(variantOf(libs.jna) { artifactType("aar") })
    api(libs.coroutines.core)
}

/** Runs a cargo command in the workspace that writes to [outputDir]. */
abstract class Cargo : Exec() {
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        workingDir = project.rootDir.parentFile
        // cargo knows what changed in the workspace; Gradle does not.
        outputs.upToDateWhen { false }
    }
}

// The host library carries the metadata uniffi-bindgen generates the bindings from.
val hostBuild = tasks.register<Exec>("cargoBuildHost") {
    workingDir = repo
    commandLine("cargo", "build", "-p", "herder-ffi", "--features", "bindgen", "--lib", "--bin", "uniffi-bindgen")
}

androidComponents {
    onVariants { variant ->
        val name = variant.name.replaceFirstChar(Char::uppercase)
        val bindings = tasks.register<Cargo>("uniffiBindings$name") {
            dependsOn(hostBuild)
            val target = repo.resolve("target/debug")
            commandLine(
                target.resolve("uniffi-bindgen").path, "generate",
                "--library", target.resolve(System.mapLibraryName("herder_ffi")).path,
                "--language", "kotlin", "--no-format",
            )
            argumentProviders += CommandLineArgumentProvider {
                listOf("--out-dir", outputDir.get().asFile.path)
            }
        }
        variant.sources.java?.addGeneratedSourceDirectory(bindings, Cargo::outputDir)

        // Release libraries for every variant: a debug build of the Rust side is large and slow.
        val libraries = tasks.register<Cargo>("cargoNdk$name") {
            commandLine("cargo", "ndk", "-t", "arm64-v8a", "-t", "x86_64")
            argumentProviders += CommandLineArgumentProvider {
                listOf("-o", outputDir.get().asFile.path, "build", "-p", "herder-ffi", "--release")
            }
        }
        variant.sources.jniLibs?.addGeneratedSourceDirectory(libraries, Cargo::outputDir)
    }
}
